services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - '6034:3306' # Binding external port 6033 to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - app_network
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_app_service
    restart: always
    ports:
      - '9999:80' # Binding external port 9999 to container port 80
    environment:
      PMA_HOST: mysql # Host of the MySQL service
      UPLOAD_LIMIT: 4G
    depends_on:
      - mysql # Ensure MySQL starts before phpMyAdmin
    networks:
      - app_network

volumes:
  mysql-data: # Define a volume for MySQL data persistence
networks:
  app_network:
    # Define a custom network
    driver: bridge # U
